# Generated by Django 5.2.3 on 2025-06-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderuser_orders_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='benefit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
