# Generated by Django 5.2.3 on 2025-06-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='per_month_debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
