# Generated by Django 5.2.3 on 2025-07-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_per_month_debt"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderuser",
            name="tg_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
