# Generated by Django 5.2.3 on 2025-07-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_orderuser_tg_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(auto_now_add=True)),
                ("is_payment", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Date",
                "verbose_name_plural": "Payment Dates",
                "db_table": "payment_dates",
            },
        ),
    ]
