# Generated by Django 5.2.3 on 2025-07-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_paymentdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdate",
            name="payment_sum",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
