# Generated by Django 5.2.3 on 2025-07-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_paymentdate_payment_sum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
