# Generated by Django 5.2.3 on 2025-07-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_paymentdate_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='all_harm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
